version: "3.8"

services:
  api:
    build: .
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - ./uploads:/usr/src/app/uploads
    restart: unless-stopped

volumes:
  uploads:
